[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "car_dreamer"
authors = [
    {name = "Dechen Gao", email = "dcgao@ucdavis.edu"},
    {name = "Shuangyu Cai", email = "caisy21@mails.tsinghua.edu.cn"},
    {name = "Hanchu Zhou", email = "hczhou@ucdavis.edu"}
]
dynamic = ["version", "description"]
dependencies = [
    # 替换 gym 为 gymnasium（见后文“代码兼容”）
    "gymnasium>=0.28,<1",

    "flask==3.0.3",
    "opencv-python==4.8.0.*",        # 对齐 sheeprl
    "carla==0.9.15",
    "numpy>=1.26,<2",                # 放宽到 1.26.x
    "ruamel.yaml==0.18.6",
    "typing_extensions>=4.12,<5",    # 放宽到 4.12+
    "networkx==3.1",
    "Shapely==1.8.4",
    "pyyaml==6.0.1",
]

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]
